---
settings:
  name: Astra Automation 23.07
  internal:
    pdf_enabled: true
    api_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    api_enabled: false
sidebar:
  entries:
    - title: Astra Control Automation docs
      url: /index.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Astra
  repo: astra-family

homepage:
  tiles:
